In [25]:
from keras import backend as K
from keras.layers.convolutional import Conv2D, MaxPooling2D ,Conv3D
from keras.layers import Input, Dense, Activation ,Flatten
from keras.layers import Reshape, Lambda 
from keras.layers.merge import add, concatenate
from keras.layers.normalization import BatchNormalization
from keras.models import Model,Sequential
from keras.layers.recurrent import GRU
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image as ki

In [39]:
image_input = Input(shape=(224, 224, 3))

model = VGG16(input_tensor=image_input, include_top=True,weights='imagenet')

last_layer = model.get_layer('block5_pool').output
x= Flatten(name='flatten')(last_layer) 
x= Dense(128,activation='relu',name='fc1')(x)
x= Dense(128,activation='relu',name='fc2')(x)
out = Dense(2, activation='softmax', name='output')(x)
custom_vgg_model = Model(image_input, out)


for layer in custom_vgg_model.layers[:-3]:
    layer.trainable = False


custom_vgg_model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])


In [40]:
custom_vgg_model.load_weights("InvoiceClassifier.h5")

In [41]:
from PIL import Image as im
import numpy as np
size = (224,224)

In [84]:
prediction_dict = {}
image_dir = "mix\\"
import os
for pic in os.listdir(image_dir):
        img = im.open(image_dir+pic)
        img =img.resize(size,) 
        img_array = ki.img_to_array(img)
        img_array = np.expand_dims(img_array,axis=0)
        try:
            prediction = custom_vgg_model.predict(img_array)
            print(prediction)
            prediction_dict[pic]= {"type":"Invoice",} if prediction.argmax() else  {"type":"Flower" }
        except:
            pass

[[6.772593e-22 1.000000e+00]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]


{'adhar.jpg': {'type': 'Invoice'},
 'birth_month_flowers_primary_1920x1280px_pixabay.jpg': {'type': 'Flower'},
 'butterfly_flower_01_hd_pictures_166973.jpg': {'type': 'Flower'},
 'craig_burrows_uv_flowers_1.jpg': {'type': 'Flower'},
 'Creative_Farmer_Red_Rose_Flower_SDL438762962_1_e60ab.jpeg': {'type': 'Flower'},
 'dahlia_red_blossom_bloom_60597.jpeg': {'type': 'Flower'},
 'daisy_pollen_flower_nature_87840.jpeg': {'type': 'Flower'},
 'Dedicated_Love_large.jpg': {'type': 'Flower'},
 'di9raM7nT.jpg': {'type': 'Flower'},
 'dsc_0598_edit.jpg': {'type': 'Flower'},
 'FCO_VAL_289.jpg': {'type': 'Flower'},
 'pic_006.jpg': {'type': 'Invoice'},
 'pic_007.jpg': {'type': 'Invoice'},
 'pic_008.jpg': {'type': 'Invoice'},
 'pic_010.jpg': {'type': 'Invoice'},
 'pic_011.jpg': {'type': 'Invoice'},
 'pic_012.jpg': {'type': 'Invoice'},
 'pic_013.jpg': {'type': 'Invoice'},
 'pic_017.jpg': {'type': 'Invoice'},
 'pic_019.jpg': {'type': 'Invoice'},
 'pic_022.jpg': {'type': 'Invoice'},
 'pic_023.png': {'type':